name: Clang Windows build

on: [push]
#    branches: [master]
env:
  CMAKE_VERSION: 3.16.2
  NINJA_VERSION: 1.10.0

    #on:
    #  [push]
    #  workflow_dispatch:
    #    inputs:
    #      build_target:
    #        required: true
    #        type: string

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-2022,
            build_type: Release,
            cxx: "cl",
            cc: "cl",
            llvm_version: "14.0.0",
          }

    steps:
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - uses: actions/checkout@v2
      with:
        repository: 'llvm/llvm-project'
        ref: 'llvmorg-${{ matrix.config.llvm_version }}'
        path: 'llvm-project'

    - name: Configure
      run: |
        mkdir clang-14
        cmake -S $env:GITHUB_WORKSPACE/llvm-project/llvm -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=OFF -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DCLANG_ENABLE_ARCMT=OFF -DCMAKE_INSTALL_UCRT_LIBRARIES=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE/clang-14

        #        -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD="" -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_C_FLAGS_DEBUG="-g1 -Og" -DCMAKE_CXX_FLAGS_DEBUG="-g1 -Og" -DCMAKE_INSTALL_PREFIX=`pwd`/install llvm

        #    - name: Configure
        #      uses: llvm/actions/build-test-llvm-project@main
        #      with:
        #        cmake_args: '-B build -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=OFF -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DCLANG_ENABLE_ARCMT=OFF -DCMAKE_INSTALL_UCRT_LIBRARIES=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE/clang-14"'
          #        build_target:  '${{ inputs.build_target }}'

    - name: Build
      continue-on-error: false
      run: |
        # Make sure all of LLVM libraries that llvm-config needs are built.
        ninja -C build
        ninja -C build install

    - name: Show
      shell: bash
      run: |
          ls -l

          #    - name: Install
          #      #      shell: cmake -P {0}
          #      continue-on-error: false
          #      run: |
          #        ninja -C build install
        #        file(MAKE_DIRECTORY "$ENV{GITHUB_WORKSPACE}/clang-14")
        #        execute_process(
        #          cmake --build build --config Release --target install
        #          RESULT_VARIABLE result
        #        )
        #        if (NOT result EQUAL 0)
        #          message(FATAL_ERROR "Bad exit status")
        #        endif()

    - name: Show
      shell: bash
      run: |
          rm -rf build # we need disk space
          ls -l clang-14

    - name: Create archive
      id: install_clang_10
      shell: cmake -P {0}
      run: |
        set(llvm_version ${{ matrix.config.llvm_version }})
        set(path_separator ";")

        file(MAKE_DIRECTORY "$ENV{GITHUB_WORKSPACE}/archive")
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar cvz "$ENV{GITHUB_WORKSPACE}/archive/llvm+clang-${{ matrix.config.llvm_version }}-win64-msvc-release.tar.xz" -- "$ENV{GITHUB_WORKSPACE}/clang-14/")

        # Fetch LLVM/clang from LLVM for macOS
        file(DOWNLOAD "https://github.com/llvm/llvm-project/releases/download/llvmorg-${llvm_version}/clang+llvm-${llvm_version}-x86_64-apple-darwin.tar.xz" "$ENV{GITHUB_WORKSPACE}/archive/clang+llvm-${llvm_version}-x86_64-apple-darwin.tar.xz")

    - name: Upload binary to GH
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ github.workspace }}/archive/*.xz
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ matrix.config.llvm_version }}
        overwrite: false
        file_glob: true
